### PR TITLE
Added content and pictures

### PR DESCRIPTION
**Pull request by kiddi**
Added content team, about, and guidelines pages.

The markdown is very ugly though, needs some styling.

Also changed some pictures and stuff on the front page.

### CODE REVIEW

**Comment by kristjanmik** [comment]
LGTM

**Comment by johannth** [comment]
This did not go live. CI failed. I'm restarting it.

**Comment by johannth** [comment]
Hmm, did not work. Trying locally.

**Comment by johannth** [comment]
Deploying locally did work.

**Comment by kristjanmik** [comment]
@johannth did you look into why it did not work remotely?

**Pull request merged**
