### PR TITLE
Better readme

### PR DESCRIPTION
**Pull request by kristjanmik**

### CODE REVIEW

**Comment by johannth** [comment]
This works and starts the project. I made minor clarifications and added links to tools in #3.

I get the following error though:

```
SequelizeConnectionError: password authentication failed for user "johannth"
```

because I haven't created any SQL database. What are the plans for that? Is it still in one of the other repos? Or should we add it to `package.json`?

**Comment by kristjanmik** [comment]
@johannth we are not there yet with the database. It is something we have to add to the flow/package.json at some point. Will try to fix later today.

**Comment by kristjanmik** [comment]
If you install postgres and create a database named communityfund the problem should go away.

**Comment by kristjanmik** [comment]
I will merge this and move the DB discussion to #4

**Pull request merged**
